set(SOURCE_GROUP_HEADER_FILES
    ${CMAKE_CURRENT_LIST_DIR}/RicImportEnsembleFilesetFeature.h
    ${CMAKE_CURRENT_LIST_DIR}/RicCreateEnsembleFromFilesetFeature.h
)

set(SOURCE_GROUP_SOURCE_FILES
    ${CMAKE_CURRENT_LIST_DIR}/RicImportEnsembleFilesetFeature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RicCreateEnsembleFromFilesetFeature.cpp
)

list(APPEND COMMAND_CODE_HEADER_FILES ${SOURCE_GROUP_HEADER_FILES})
list(APPEND COMMAND_CODE_SOURCE_FILES ${SOURCE_GROUP_SOURCE_FILES})
