name: Check Code Format

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Check src format
      uses: gnuradio/clang-format-lint-action@v0.5-4
      with:
        source: './ApplicationCode'
        exclude: './ApplicationCode/FileInterface'
        extensions: 'h,cpp'
        clangFormatVersion: 6
