name: Update Submodules

on:
  schedule:
    - cron: '0 0 * * 0' # Runs every Sunday at midnight
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  update-submodules:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        submodule: 
          - tomlplusplus

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install GitHub CLI
        run: sudo apt-get install -y gh

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Update submodules to latest release
        run: |
          cd ThirdParty/${{ matrix.submodule }}
          git fetch --tags
          latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)

          if [ -n "$latest_tag" ]; then
            git checkout $latest_tag
          else
            echo "Empty tag detected in ${{ matrix.submodule }}. Nothing to do."
          fi

      - uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update ${{ matrix.submodule }}"
          title: "Update ${{ matrix.submodule }}"
          branch: ci-update-${{ matrix.submodule }}
          branch-suffix: random
