name: Update Submodules

on:
  schedule:
    - cron: '0 0 * * 0' # Runs every Sunday at midnight
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  update-submodules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install GitHub CLI
        run: sudo apt-get install -y gh

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Update submodules to latest release
        run: |
          cd ThirdParty
          submodules=("fast_float" "spdlog" ) # Specify your submodules here
          for submodule in "${submodules[@]}"; do
            git branch HEAD:update-$submodule
            cd $submodule
            git fetch --tags
            latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
            git checkout $latest_tag
            cd ..
            git add $submodule
            git commit -m "Update $submodule to latest release" || echo "No changes to commit"
            git push origin HEAD:update-$submodule
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Pull Requests for each submodule
        run: |
          submodules=("fast_float" "spdlog") # Specify your submodules here
          for submodule in "${submodules[@]}"; do
            gh auth login --with-token <<< ${{ secrets.GITHUB_TOKEN }}
            gh pr create --title "Update $submodule to latest release" --body "This PR updates the $submodule submodule to its latest release." --head update-$submodule --base main
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
