set(SOURCE_GROUP_HEADER_FILES
    ${CMAKE_CURRENT_LIST_DIR}/RimEnsembleFileset.h
    ${CMAKE_CURRENT_LIST_DIR}/RimEnsembleFilesetCollection.h
)

set(SOURCE_GROUP_SOURCE_FILES
    ${CMAKE_CURRENT_LIST_DIR}/RimEnsembleFileset.cpp
    ${CMAKE_CURRENT_LIST_DIR}/RimEnsembleFilesetCollection.cpp
)

list(APPEND CODE_HEADER_FILES ${SOURCE_GROUP_HEADER_FILES})
list(APPEND CODE_SOURCE_FILES ${SOURCE_GROUP_SOURCE_FILES})
